-- ERP Dom Pedro — cadastros iniciais (etapa 3).
-- Gerado do dados.js da v31 (matriz e perfis já com as decisões
-- de 02/10). Os LANÇAMENTOS de exemplo não entram: o banco
-- nasce com cadastro, não com movimento.
--
-- RODA ANTES do 02-rls.sql. O `force row level security` vale
-- até para o dono da tabela; só não morde porque o papel do
-- Supabase tem BYPASSRLS. Semear antes de ligar a RLS funciona
-- nos dois casos.

-- empresas
insert into empresas (id,apelido,nome,cnpj,municipio,uf,codigo_ibge,inscricao_municipal,matriz,ativo) values ('emp1','HJM Matriz','HJM DOM PEDRO GESTAO E SERVICOS EM SAUDE LTDA','34.958.609/0001-90','BARUERI','SP','3505708','5BX8969',true,true);
insert into empresas (id,apelido,nome,cnpj,municipio,uf,codigo_ibge,inscricao_municipal,matriz,ativo) values ('emp2','HJM Filial CE','HJM DOM PEDRO GESTAO E SERVICOS EM SAUDE LTDA','34.958.609/0003-51','FORTALEZA','CE','2304400','',false,true);
insert into empresas (id,apelido,nome,cnpj,municipio,uf,codigo_ibge,inscricao_municipal,matriz,ativo) values ('emp3','Novaped','NOVAPED PROFISSIONAIS ESPECIALIZADOS DE SAUDE LTDA','34.015.981/0001-62','','','','',false,true);

-- perfis
insert into perfis (id,nome,sistema,acoes) values ('assistente','Assistente financeiro',true,'["lancar","pagar","faturar","ver_custo","estoque","requisitar","comprar","receber","autorizar_faturamento","ver_dados_pessoais"]'::jsonb);
insert into perfis (id,nome,sistema,acoes) values ('diretoria','Diretoria',true,'["lancar","pagar","aprovar","cancelar","estornar","faturar","ver_custo","estoque","requisitar","comprar","aprovar_compra","receber","dp","ver_dados_pessoais","ver_pacientes","autorizar_faturamento","liberar_faturamento","baixar_ativo"]'::jsonb);
insert into perfis (id,nome,sistema,acoes) values ('socio','Sócio',true,'["lancar","pagar","aprovar","cancelar","estornar","faturar","ver_custo","estoque","requisitar","comprar","aprovar_compra","receber","dp","ver_dados_pessoais","ver_pacientes","autorizar_faturamento","liberar_faturamento","baixar_ativo"]'::jsonb);
insert into perfis (id,nome,sistema,acoes) values ('admin','Administração',true,'["lancar","pagar","aprovar","cancelar","estornar","faturar","ver_custo","estoque","requisitar","comprar","aprovar_compra","receber","dp","ver_dados_pessoais","ver_pacientes","baixar_ativo","autorizar_faturamento","liberar_faturamento","admin"]'::jsonb);
insert into perfis (id,nome,sistema,acoes) values ('consulta','Consulta',true,'["ver_custo"]'::jsonb);
insert into perfis (id,nome,sistema,acoes) values ('estoquista','Controle de estoque',false,'["estoque","requisitar","receber","ver_pacientes"]'::jsonb);
insert into perfis (id,nome,sistema,acoes) values ('comprador','Compras',false,'["requisitar","comprar","receber","estoque"]'::jsonb);
insert into perfis (id,nome,sistema,acoes) values ('operacional','Operacional — centro cirúrgico',false,'["estoque","ver_pacientes"]'::jsonb);
insert into perfis (id,nome,sistema,acoes) values ('dp','Departamento Pessoal',false,'["dp","ver_dados_pessoais"]'::jsonb);
insert into perfis (id,nome,sistema,acoes) values ('produtividade_dir','Diretoria de produtividade',false,'["produtividade","lancar","faturar","autorizar_faturamento","ver_custo","receber"]'::jsonb);
insert into perfis (id,nome,sistema,acoes) values ('produtividade_ger','Gerência de produtividade',false,'["produtividade","lancar","faturar","autorizar_faturamento","ver_custo","receber"]'::jsonb);

-- matriz de acesso: perfil × módulo → níveis VMFA
insert into matriz_acesso (perfil,modulo,niveis) values ('assistente','financeiro','VMF');
insert into matriz_acesso (perfil,modulo,niveis) values ('assistente','produtividade','VMF');
insert into matriz_acesso (perfil,modulo,niveis) values ('assistente','estoque','VF');
insert into matriz_acesso (perfil,modulo,niveis) values ('assistente','ativos','VMF');
insert into matriz_acesso (perfil,modulo,niveis) values ('assistente','faturamento','VMF');
insert into matriz_acesso (perfil,modulo,niveis) values ('assistente','compras','VMF');
insert into matriz_acesso (perfil,modulo,niveis) values ('assistente','contratos','VMF');
insert into matriz_acesso (perfil,modulo,niveis) values ('assistente','dp','VF');
insert into matriz_acesso (perfil,modulo,niveis) values ('assistente','cadastros','VM');
insert into matriz_acesso (perfil,modulo,niveis) values ('assistente','procedimentos','VF');
insert into matriz_acesso (perfil,modulo,niveis) values ('assistente','administracao','V');
insert into matriz_acesso (perfil,modulo,niveis) values ('diretoria','financeiro','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('diretoria','produtividade','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('diretoria','estoque','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('diretoria','ativos','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('diretoria','faturamento','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('diretoria','compras','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('diretoria','contratos','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('diretoria','dp','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('diretoria','cadastros','VMA');
insert into matriz_acesso (perfil,modulo,niveis) values ('diretoria','procedimentos','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('diretoria','administracao','VM');
insert into matriz_acesso (perfil,modulo,niveis) values ('socio','financeiro','VFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('socio','produtividade','VFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('socio','estoque','VFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('socio','ativos','VFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('socio','faturamento','VFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('socio','compras','VFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('socio','contratos','VFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('socio','dp','VFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('socio','cadastros','VA');
insert into matriz_acesso (perfil,modulo,niveis) values ('socio','procedimentos','VFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('socio','administracao','VM');
insert into matriz_acesso (perfil,modulo,niveis) values ('admin','financeiro','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('admin','produtividade','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('admin','estoque','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('admin','ativos','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('admin','faturamento','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('admin','compras','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('admin','contratos','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('admin','dp','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('admin','cadastros','VMA');
insert into matriz_acesso (perfil,modulo,niveis) values ('admin','procedimentos','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('admin','administracao','VMA');
insert into matriz_acesso (perfil,modulo,niveis) values ('consulta','financeiro','VF');
insert into matriz_acesso (perfil,modulo,niveis) values ('consulta','produtividade','VF');
insert into matriz_acesso (perfil,modulo,niveis) values ('consulta','estoque','VF');
insert into matriz_acesso (perfil,modulo,niveis) values ('consulta','ativos','VF');
insert into matriz_acesso (perfil,modulo,niveis) values ('consulta','faturamento','VF');
insert into matriz_acesso (perfil,modulo,niveis) values ('consulta','compras','VF');
insert into matriz_acesso (perfil,modulo,niveis) values ('consulta','contratos','VF');
insert into matriz_acesso (perfil,modulo,niveis) values ('consulta','dp','VF');
insert into matriz_acesso (perfil,modulo,niveis) values ('consulta','cadastros','V');
insert into matriz_acesso (perfil,modulo,niveis) values ('consulta','procedimentos','VF');
insert into matriz_acesso (perfil,modulo,niveis) values ('consulta','administracao','');
insert into matriz_acesso (perfil,modulo,niveis) values ('estoquista','financeiro','');
insert into matriz_acesso (perfil,modulo,niveis) values ('estoquista','produtividade','');
insert into matriz_acesso (perfil,modulo,niveis) values ('estoquista','estoque','VM');
insert into matriz_acesso (perfil,modulo,niveis) values ('estoquista','ativos','VM');
insert into matriz_acesso (perfil,modulo,niveis) values ('estoquista','faturamento','');
insert into matriz_acesso (perfil,modulo,niveis) values ('estoquista','compras','VM');
insert into matriz_acesso (perfil,modulo,niveis) values ('estoquista','contratos','');
insert into matriz_acesso (perfil,modulo,niveis) values ('estoquista','dp','');
insert into matriz_acesso (perfil,modulo,niveis) values ('estoquista','cadastros','V');
insert into matriz_acesso (perfil,modulo,niveis) values ('estoquista','procedimentos','VM');
insert into matriz_acesso (perfil,modulo,niveis) values ('estoquista','administracao','');
insert into matriz_acesso (perfil,modulo,niveis) values ('comprador','financeiro','');
insert into matriz_acesso (perfil,modulo,niveis) values ('comprador','produtividade','');
insert into matriz_acesso (perfil,modulo,niveis) values ('comprador','estoque','VM');
insert into matriz_acesso (perfil,modulo,niveis) values ('comprador','ativos','V');
insert into matriz_acesso (perfil,modulo,niveis) values ('comprador','faturamento','');
insert into matriz_acesso (perfil,modulo,niveis) values ('comprador','compras','VMF');
insert into matriz_acesso (perfil,modulo,niveis) values ('comprador','contratos','');
insert into matriz_acesso (perfil,modulo,niveis) values ('comprador','dp','');
insert into matriz_acesso (perfil,modulo,niveis) values ('comprador','cadastros','V');
insert into matriz_acesso (perfil,modulo,niveis) values ('comprador','procedimentos','');
insert into matriz_acesso (perfil,modulo,niveis) values ('comprador','administracao','');
insert into matriz_acesso (perfil,modulo,niveis) values ('dp','financeiro','');
insert into matriz_acesso (perfil,modulo,niveis) values ('dp','produtividade','');
insert into matriz_acesso (perfil,modulo,niveis) values ('dp','estoque','');
insert into matriz_acesso (perfil,modulo,niveis) values ('dp','ativos','');
insert into matriz_acesso (perfil,modulo,niveis) values ('dp','faturamento','');
insert into matriz_acesso (perfil,modulo,niveis) values ('dp','compras','');
insert into matriz_acesso (perfil,modulo,niveis) values ('dp','contratos','');
insert into matriz_acesso (perfil,modulo,niveis) values ('dp','dp','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('dp','cadastros','V');
insert into matriz_acesso (perfil,modulo,niveis) values ('dp','procedimentos','');
insert into matriz_acesso (perfil,modulo,niveis) values ('dp','administracao','');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_dir','financeiro','');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_dir','produtividade','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_dir','estoque','');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_dir','ativos','VF');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_dir','faturamento','VMF');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_dir','compras','');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_dir','contratos','VMF');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_dir','dp','');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_dir','cadastros','V');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_dir','procedimentos','VFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_dir','administracao','');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_ger','financeiro','');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_ger','produtividade','VMFA');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_ger','estoque','');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_ger','ativos','');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_ger','faturamento','VMF');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_ger','compras','');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_ger','contratos','VMF');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_ger','dp','');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_ger','cadastros','V');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_ger','procedimentos','V');
insert into matriz_acesso (perfil,modulo,niveis) values ('produtividade_ger','administracao','');
insert into matriz_acesso (perfil,modulo,niveis) values ('operacional','financeiro','');
insert into matriz_acesso (perfil,modulo,niveis) values ('operacional','produtividade','');
insert into matriz_acesso (perfil,modulo,niveis) values ('operacional','estoque','VM');
insert into matriz_acesso (perfil,modulo,niveis) values ('operacional','ativos','');
insert into matriz_acesso (perfil,modulo,niveis) values ('operacional','faturamento','');
insert into matriz_acesso (perfil,modulo,niveis) values ('operacional','compras','');
insert into matriz_acesso (perfil,modulo,niveis) values ('operacional','contratos','');
insert into matriz_acesso (perfil,modulo,niveis) values ('operacional','dp','');
insert into matriz_acesso (perfil,modulo,niveis) values ('operacional','cadastros','');
insert into matriz_acesso (perfil,modulo,niveis) values ('operacional','procedimentos','VM');
insert into matriz_acesso (perfil,modulo,niveis) values ('operacional','administracao','');

-- usuários (o login vem por convite, no painel do Supabase)
insert into usuarios (id,nome,perfil,ativo) values ('u1','Dayana (assist. financeiro)','assistente',true);
insert into usuarios (id,nome,perfil,ativo) values ('u2','Márcia (diretora financeira)','diretoria',true);
insert into usuarios (id,nome,perfil,ativo) values ('u3','Fellype (sócio)','socio',true);
insert into usuarios (id,nome,perfil,ativo) values ('u4','Contabilidade (consulta)','consulta',true);
insert into usuarios (id,nome,perfil,ativo) values ('u5','Administrador','admin',true);
insert into usuarios (id,nome,perfil,ativo) values ('u6','Monique Cardoso (estoque)','estoquista',true);
insert into usuarios (id,nome,perfil,ativo) values ('u7','Compras (a definir)','comprador',true);
insert into usuarios (id,nome,perfil,ativo) values ('u8','Carol (DP)','dp',true);
insert into usuarios (id,nome,perfil,ativo) values ('u9','Romário (assist. financeiro)','assistente',true);
insert into usuarios (id,nome,perfil,ativo) values ('u10','David (sócio)','socio',true);
insert into usuarios (id,nome,perfil,ativo) values ('u11','Bianca (diretoria de produtividade)','produtividade_dir',true);
insert into usuarios (id,nome,perfil,ativo) values ('u12','Monique Almeida (gerência de produtividade)','produtividade_ger',true);
insert into usuarios (id,nome,perfil,ativo) values ('u13','Operacional HGB (centro cirúrgico)','operacional',true);

-- plano de contas (tipo só no nível 1; pai liga a conta ao grupo)
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('1','Receita operacional',1,'receita',null);
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('1.01','Serviços médicos',2,null,'1');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('1.02','Locação de equipamentos',2,null,'1');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('1.03','Outras receitas',2,null,'1');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('1.04','Alienação de imobilizado',2,null,'1');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('2','Impostos de venda',1,'deducao',null);
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('2.01','ISS',2,null,'2');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('2.02','PIS',2,null,'2');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('2.03','COFINS',2,null,'2');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('2.04','IRPJ',2,null,'2');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('2.05','CSLL',2,null,'2');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('2.06','ICMS',2,null,'2');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('2.07','Parcelamentos de impostos',2,null,'2');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('2.08','Outros impostos',2,null,'2');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('3','Custos diretos',1,'custo',null);
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('3.01','Serviços médicos — produção',2,null,'3');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('3.02','Custos de locações',2,null,'3');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('3.03','Outros custos diretos',2,null,'3');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('4','Despesas com pessoal',1,'despesa',null);
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('4.01','Folha de pagamento',2,null,'4');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('4.02','Benefícios',2,null,'4');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('4.03','FGTS',2,null,'4');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('4.04','INSS',2,null,'4');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('4.05','Férias',2,null,'4');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('4.06','13º salário',2,null,'4');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('4.07','Rescisões',2,null,'4');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('4.08','Outros encargos',2,null,'4');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('5','Despesas com P&D',1,'despesa',null);
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('5.01','Desenvolvimento de software — telemedicina',2,null,'5');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('6','Despesas administrativas',1,'despesa',null);
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('6.01','Aluguéis',2,null,'6');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('6.02','Certificações',2,null,'6');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('6.03','Honorários contábeis',2,null,'6');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('6.04','Honorários de consultoria',2,null,'6');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('6.05','Despesas com viagens',2,null,'6');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('6.06','Reembolsos',2,null,'6');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('6.07','Manutenção e conservação',2,null,'6');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('6.08','Segurança e rastreamento',2,null,'6');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('6.09','Cartão corporativo',2,null,'6');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('6.10','Ativo fixo',2,null,'6');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('6.11','Outros',2,null,'6');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('7','Tecnologia da informação',1,'despesa',null);
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('7.01','Sistemas de gestão (ERP)',2,null,'7');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('7.02','Software médico',2,null,'7');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('7.03','Sistemas / TI',2,null,'7');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('7.04','Telecomunicações',2,null,'7');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('8','Despesas operacionais',1,'despesa',null);
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('8.01','Locação de veículos',2,null,'8');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('8.02','Financiamentos',2,null,'8');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('8.03','Energia elétrica',2,null,'8');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('8.04','Material médico-hospitalar',2,null,'8');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('8.05','Frete e logística',2,null,'8');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('8.06','Outros',2,null,'8');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('9','Despesas financeiras',1,'despesa',null);
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('9.01','Despesa bancária',2,null,'9');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('9.02','Empréstimos e financiamentos',2,null,'9');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('9.03','Encargos financeiros',2,null,'9');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('9.04','Juros de atraso',2,null,'9');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('10','Aportes e retiradas',1,'nao_operacional',null);
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('10.01','Retiradas de sócios',2,null,'10');
insert into plano_contas (cod,nome,nivel,tipo,pai) values ('10.02','Aportes de sócios',2,null,'10');

-- centros de custo e projetos
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('cc100','Matriz SP','100','Matriz — Barueri/SP','matriz',null,'Barueri','SP','34958609000190',null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('cc200','Filial RJ','200','Filial — Petrópolis/RJ','filial',null,'Petrópolis','RJ',null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('cc300','Filial CE','300','Filial — Fortaleza/CE','filial',null,'Fortaleza','CE',null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('cc900','Geral','900','Geral (sem projeto)','geral',null,null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj01','PRISIONAL','001','PRISIONAL','projeto','Fortaleza',null,null,null,null,'cl08',null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj02','CIDH','002','CIDH','projeto','Fortaleza',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj03','CDERM','003','CDERM','projeto','Fortaleza',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj04','CCAD','004','CCAD','projeto','Fortaleza',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj05','HSMM','005','HSMM','projeto','Fortaleza',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj06','HEMOCE','006','HEMOCE','projeto','Fortaleza',null,null,null,null,'cl07',null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj07','IJF','007','IJF','projeto','Fortaleza',null,null,null,null,'cl06',null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj08','SCFORT - Tomografia','008','SCFORT - Tomografia','projeto','Fortaleza',null,null,null,null,'cl05',null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj09','GHC - UPA','009','GHC - UPA','projeto','POA',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj10','GHC - ANESTESIA POA','010','GHC - ANESTESIA POA','projeto','GHC - Anestesia POA',null,null,null,null,'cl04',null,null,false);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj11','GHC - HGB ANESTESIA','011','GHC - HGB — Anestesia','projeto','Bonsucesso',null,null,null,null,'cl03','GHC - HGB',null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj44','GHC - HGB CARDIOLOGIA','044','GHC - HGB — Cardiologia','projeto','Bonsucesso',null,null,null,null,null,'GHC - HGB',null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj45','GHC - HGB CTI PEDIATRICA','045','GHC - HGB — CTI Pediátrica','projeto','Bonsucesso',null,null,null,null,null,'GHC - HGB',null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj46','GHC - HGB EMERGENCIA ADULTO','046','GHC - HGB — Emergência adulto','projeto','Bonsucesso',null,null,null,null,null,'GHC - HGB',null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj47','GHC - HGB EMERGENCIA PEDIATRICA','047','GHC - HGB — Emergência pediátrica','projeto','Bonsucesso',null,null,null,null,null,'GHC - HGB',null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj48','GHC - HGB MEDICINA INTERNA','048','GHC - HGB — Medicina interna','projeto','Bonsucesso',null,null,null,null,null,'GHC - HGB',null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj49','GHC - HGB CORONARIANA','049','GHC - HGB — Coronariana','projeto','Bonsucesso',null,null,null,null,null,'GHC - HGB',null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj50','GHC - HGB MUTIRAO','050','GHC - HGB — Mutirão','projeto','Bonsucesso',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj51','HGB MUTIRAO OFTALMO','050.1','GHC - HGB Mutirão — Oftalmologia','projeto','Bonsucesso',null,null,null,null,null,'GHC - HGB MUTIRAO','OFTALMO',true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj52','HGB MUTIRAO CIR GERAL','050.2','GHC - HGB Mutirão — Cirurgia geral','projeto','Bonsucesso',null,null,null,null,null,'GHC - HGB MUTIRAO','CIRURGIA GERAL',true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj53','HGB MUTIRAO UROLOGIA','050.3','GHC - HGB Mutirão — Urologia','projeto','Bonsucesso',null,null,null,null,null,'GHC - HGB MUTIRAO','UROLOGIA',true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj54','HGB MUTIRAO OTORRINO','050.4','GHC - HGB Mutirão — Otorrinolaringologia','projeto','Bonsucesso',null,null,null,null,null,'GHC - HGB MUTIRAO','OTORRINO',true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj55','HGB MUTIRAO GINECO','050.5','GHC - HGB Mutirão — Ginecologia','projeto','Bonsucesso',null,null,null,null,null,'GHC - HGB MUTIRAO','GINECO',true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj56','HGB MUTIRAO RISCO CX','050.6','GHC - HGB Mutirão — Risco cirúrgico','projeto','Bonsucesso',null,null,null,null,null,'GHC - HGB MUTIRAO','RISCO CX',true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj12','IRON TRAINERS - Enfermagem','012','IRON TRAINERS - Enfermagem','projeto','Iron Trainers',null,null,null,null,'cl12',null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj13','IRON TRAINERS - FUP','013','IRON TRAINERS - FUP','projeto','Iron Trainers',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj14','IRON TRAINERS - Psicólogo','014','IRON TRAINERS - Psicólogo','projeto','Iron Trainers',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj15','IRON TRAINERS - AGP','015','IRON TRAINERS - AGP','projeto','Iron Trainers',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj16','HMTSM - PJ','016','HMTSM - PJ','projeto','HMTSM',null,null,null,null,'cl15',null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj17','HMTSM - Multidisciplinares','017','HMTSM - Multidisciplinares','projeto','HMTSM',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj18','AGIR - HMSA - CIR GERAL','018','AGIR - HMSA - CIR GERAL','projeto','Sant''ana',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj19','AGIR - HMSA - GO','019','AGIR - HMSA - GO','projeto','Sant''ana',null,null,null,null,'cl01',null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj20','AGIR - HMSA - ANESTESIA','020','AGIR - HMSA - ANESTESIA','projeto','Sant''ana',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj21','AGIR - HMSA - NEO','021','AGIR - HMSA - NEO','projeto','Sant''ana',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj22','IBD SOCIAL - SAMU','022','IBD SOCIAL - SAMU','projeto','Petrópolis',null,null,null,null,'cl09',null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj23','SCBM - ANESTESIA','023','SCBM - ANESTESIA','projeto','SCBM',null,null,null,null,'cl02',null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj24','SCBM - NEO','024','SCBM - NEO','projeto','SCBM',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj25','SCBM - CIR GERAL','025','SCBM - CIR GERAL','projeto','SCBM',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj26','SCBM - ANESTESIA PARTICULARES/CONVÊNIOS','026','SCBM - ANESTESIA PARTICULARES/CONVÊNIOS','projeto','SCBM',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj27','SCBM - PEDIATRIA','027','SCBM - PEDIATRIA','projeto','SCBM',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj28','HMSM - POA','028','HMSM - POA','projeto','HMSM',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj29','HNSN - Navegantes','029','HNSN - Navegantes','projeto','HNSN',null,null,null,null,'cl10',null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj30','Dr. Consulta - USG','030','Dr. Consulta - USG','projeto','Dr. Consulta',null,null,null,null,'cl14',null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj31','SPDM - Lusmar','031','SPDM - Lusmar','projeto','SPDM',null,null,null,null,'cl13',null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj32','SPDM - Randal','032','SPDM - Randal','projeto','SPDM',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj33','CETHID - NOVAPED','033','CETHID - NOVAPED','projeto','Maternidade Queimados',null,null,null,'emp3',null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj34','HMMQ - NOVAPED','034','HMMQ - NOVAPED','projeto','Maternidade Queimados',null,null,null,'emp3',null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj35','HMMQ MULTI - NOVAPED','035','HMMQ MULTI - NOVAPED','projeto','Maternidade Queimados',null,null,null,'emp3',null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj36','IPADE/UNICRISTUS','036','IPADE/UNICRISTUS','projeto','Fortaleza',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj37','Fund. Edson Queiroz/UNIFOR','037','Fund. Edson Queiroz/UNIFOR','projeto','Fortaleza',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj38','SCFORT - Intensificador','038','SCFORT - Intensificador','projeto','Fortaleza',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj39','SCFORT - Intensificador GE OEC','039','SCFORT - Intensificador GE OEC','projeto','Fortaleza',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj40','SCFORT - Mesa Cirúrgica','040','SCFORT - Mesa Cirúrgica','projeto','Fortaleza',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj41','Nilópolis - Santa Casa','041','Nilópolis - Santa Casa','projeto','Nilópolis',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj42','Moacyr do Carmo - Diálise','042','Moacyr do Carmo - Diálise','projeto','Duque de Caxias',null,null,null,null,null,null,null,true);
insert into centros (id,curto,codigo,nome,tipo,unidade,cidade,uf,cnpj,empresa,cliente,grupo_faturamento,especialidade_pate,ativo) values ('pj43','SAMU - Nova Friburgo','043','SAMU - Nova Friburgo','projeto','Nova Friburgo',null,null,null,null,null,null,null,true);

-- clientes
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl01','AGIR — Ass. de Gestão, Inovação e Resultados em Saúde','05029600000287','pj19',35,'RIO DE JANEIRO','RJ',true);
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl02','Santa Casa de Misericórdia de Barra Mansa','28683712000171','pj23',40,null,null,true);
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl03','Grupo Hospitalar Conceição — Hospital Federal de Bonsucesso','92787118002416','pj11',40,null,null,true);
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl04','Grupo Hospitalar Conceição S.A.','92787118000553','pj10',40,null,null,true);
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl05','Irmandade Beneficente da Santa Casa da Misericórdia de Fortaleza','07273592000164','pj08',30,null,null,true);
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl06','Instituto Dr. José Frota — IJF','07835044000180','pj07',30,null,null,true);
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl07','Centro de Hematologia e Hemoterapia do Ceará — HEMOCE','07954571011491','pj06',30,null,null,true);
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl08','Polícia Militar do Ceará','01790944003350','pj01',30,null,null,true);
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl09','IBDSOCIAL','05843874000124','pj22',30,null,null,true);
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl10','Instituto Brasileiro de Saúde, Ensino, Pesquisa e Extensão','07836454000146','pj29',60,null,null,true);
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl11','Inst. Bras. de Saúde, Ensino, Pesq. e Extensão (filial)','07836454002009','pj29',60,null,null,true);
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl12','Iron Trainers do Brasil Ltda','21298287000158','pj12',20,null,null,true);
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl13','SPDM/PAIS — Ass. Paulista para o Desenvolvimento da Medicina','61699567009300','pj31',null,null,null,true);
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl14','Dr. Consulta Centro Médico Ltda','14245016000179','pj30',null,null,null,true);
insert into clientes (id,nome,documento,centro_padrao,prazo_dias,cidade,uf,ativo) values ('cl15','Sociedade de Caridade — Santa Casa de Misericórdia Madre Michel','22351316000160','pj16',null,null,null,true);

-- credores
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr1','Dra. Marina Alves','medico','41.222.333/0001-70','3.01','pix','41.222.333/0001-70','CNPJ',true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr2','Dr. João Silva','medico','123.456.789-09','3.01','pix','(11) 98888-7777','Telefone',true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr3','MedTech Locações Ltda','fornecedor','55.444.333/0001-22','3.02','pix','financeiro@medtech.com.br','Email',true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr4','Imobiliária Centro RJ','fornecedor',null,'6.01',null,null,null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr5','Escritório Contábil','fornecedor',null,'6.03',null,null,null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr6','Receita Federal','orgao',null,'2.07','guia',null,null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr6b','Caixa Econômica Federal — FGTS','orgao',null,'4.03','guia',null,null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr7','Dr. Paulo Meireles','medico','31.884.207/0001-45','3.01','pix','31.884.207/0001-45','CNPJ',true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr8','Dra. Helena Coutinho','medico','842.117.330-52','3.01','pix','helena.coutinho@gmail.com','Email',true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr91','Dr. Rafael Amorim','medico','01234567890',null,'PIX','medico1@exemplo.com.br',null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr92','Dra. Beatriz Nunes','medico','78901234567',null,'PIX','medico2@exemplo.com.br',null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr93','Dr. Sérgio Tavares','medico','45678901234',null,'PIX','medico3@exemplo.com.br',null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr94','Dra. Camila Rocha','medico','12345678901',null,'PIX','medico4@exemplo.com.br',null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr95','Dr. Otávio Lins','medico','89012345678',null,'PIX','medico5@exemplo.com.br',null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr96','Dra. Renata Peixoto','medico','56789012345',null,'PIX','medico6@exemplo.com.br',null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr9','Dr. Sérgio Bastos','medico','19.457.882/0001-08','3.01','pix','f47ac10b-58cc-4372-a567-0e02b2c3d479','Aleatoria',true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr10','Imobiliária Alphaville','fornecedor','08.221.664/0001-31','6.01','pix','08.221.664/0001-31','CNPJ',true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr11','Enel Distribuição','fornecedor','33.050.071/0001-58','8.03','boleto',null,null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr12','Cirúrgica Nordeste Materiais','fornecedor','22.905.113/0001-77','8.04','pix','22.905.113/0001-77','CNPJ',true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr13','TOTVS S.A.','fornecedor','53.113.791/0001-22','7.01','boleto',null,null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr14','Vivo Empresas','fornecedor','02.558.157/0001-62','7.04','boleto',null,null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr15','Localiza Frotas','fornecedor','18.334.442/0001-90','8.01','pix','18.334.442/0001-90','CNPJ',true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr16','Advocacia Ribeiro & Sá','fornecedor','27.660.004/0001-13','6.04','pix','financeiro@ribeirosa.adv.br','Email',true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr17','Prefeitura de Barueri — ISS','orgao','46.523.015/0001-70','2.01','guia',null,null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr18','Banco Bradesco — empréstimo','fornecedor',null,'9.02','debito_conta',null,null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr19','Folha de pagamento','outro',null,'4.01','ted',null,null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr20','Sócios — retirada','socio',null,'10.01','ted',null,null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr21','Ar Puro Climatização','fornecedor','39.775.201/0001-64','6.07','pix','(11) 97744-2210','Telefone',true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr22','Azul Linhas Aéreas','fornecedor',null,'6.05',null,null,null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr23','Certisign Certificadora','fornecedor','01.554.285/0001-75','6.02','pix','01.554.285/0001-75','CNPJ',true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr24','Banco Bradesco','fornecedor',null,'9.01','debito_conta',null,null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('cr25','Banco Santander','fornecedor',null,'9.01','debito_conta',null,null,true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('crfn01','Camila Rodrigues Alves','funcionario','111.222.333-44','4.01','pix','111.222.333-44','CPF',true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('crfn02','Roberto Nascimento Lima','funcionario','222.333.444-55','4.01','pix','222.333.444-55','CPF',true);
insert into credores (id,nome,tipo,documento,conta_padrao,forma_pagamento,pix,tipo_chave,ativo) values ('crfn03','Juliana Ferreira Costa','funcionario','333.444.555-66','4.01','ted','',null,true);

-- contas bancárias
insert into bancos (id,empresa,apelido,banco,agencia,agencia_dv,conta,conta_dv,layout_remessa,convenio,ativo) values ('b1','emp1','Bradesco — movimento','237','01785','0','000000039464','5','cnab240','472572',true);
insert into bancos (id,empresa,apelido,banco,agencia,agencia_dv,conta,conta_dv,layout_remessa,convenio,ativo) values ('b2','emp1','Santander — movimento','033',null,null,null,null,'',null,true);
insert into bancos (id,empresa,apelido,banco,agencia,agencia_dv,conta,conta_dv,layout_remessa,convenio,ativo) values ('b3','emp2','Santander — filial CE','033','01234','','000013000567','','','',true);
insert into bancos (id,empresa,apelido,banco,agencia,agencia_dv,conta,conta_dv,layout_remessa,convenio,ativo) values ('b4','emp3','Itaú — Novaped','341','00456','','000000077889','','','',true);

-- produtos e armazéns
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr01','MT-001','Luva cirúrgica estéril 7,5','CX','40151200',20,60,128,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr02','MT-002','Seringa 20ml','CX','90183110',15,40,140.8,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr03','MT-003','Cateter venoso periférico 20G','CX','90183919',10,30,96.5,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr04','MT-004','Máscara cirúrgica tripla','CX','63079090',30,100,22.4,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr05','MT-005','Gaze estéril 7,5x7,5','PCT','30059011',40,120,8.9,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr06','MT-006','Soro fisiológico 0,9% 500ml','UN','30049099',60,200,6.75,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr07','MT-007','Equipo macrogotas','UN','90183290',50,150,3.2,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr08','MT-008','Álcool 70% 1L','UN','22072019',25,80,11.3,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr09','MT-009','Agulha 40x12','CX','90183220',12,40,18.6,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr10','MT-010','Fio de sutura nylon 3-0','CX','30061010',8,24,210,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr11','MT-011','Papel para eletrocardiógrafo','RL','48239099',10,30,14.5,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr12','MT-012','Eletrodo descartável ECG','PCT','90181910',15,50,32,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr20','CIR-001','Lente intraocular dobrável','UN','90213910',20,120,185,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr21','CIR-002','Viscoelástico 1,0ml','UN','30049099',20,120,96.5,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr22','CIR-003','Kit facoemulsificação descartável','UN','90183990',10,60,240,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr23','CIR-004','Tela de polipropileno 15x15','UN','30059090',8,40,152,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr24','CIR-005','Clipador laparoscópico descartável','UN','90183219',5,25,410,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr25','CIR-006','Trocarte descartável 10mm','UN','90183219',10,50,118,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr26','CIR-007','Fio de sutura vicryl 2-0','CX','30061010',6,30,178,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr27','CIR-008','Campo cirúrgico estéril descartável','PCT','63079090',15,80,64,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr28','CIR-009','Avental cirúrgico estéril','UN','62101000',20,100,22.5,'8.04',true);
insert into produtos (id,codigo,descricao,unidade,ncm,minimo,ideal,custo,conta,ativo) values ('pr29','CIR-010','Lâmina de bisturi 15','CX','82121020',5,25,46,'8.04',true);

insert into armazens (id,codigo,nome,centro,tipo,pai,responsavel,especialidade,ativo) values ('am01','ALM-SEDE','Almoxarifado central — Barueri','cc100','sede',null,'',null,true);
insert into armazens (id,codigo,nome,centro,tipo,pai,responsavel,especialidade,ativo) values ('am02','FARM-SCBM','Farmácia SCBM — Barra Mansa','pj23','externo',null,'Farmacêutica do projeto',null,true);
insert into armazens (id,codigo,nome,centro,tipo,pai,responsavel,especialidade,ativo) values ('am03','FARM-HMMQ','Farmácia HMMQ — Queimados','pj34','externo',null,'Farmacêutica do projeto',null,true);
insert into armazens (id,codigo,nome,centro,tipo,pai,responsavel,especialidade,ativo) values ('am04','FARM-CETHID','Farmácia CETHID — Queimados','pj33','externo',null,'',null,true);
insert into armazens (id,codigo,nome,centro,tipo,pai,responsavel,especialidade,ativo) values ('am05','ALM-HGB','Almoxarifado HGB — Bonsucesso','pj11','externo',null,'',null,true);
insert into armazens (id,codigo,nome,centro,tipo,pai,responsavel,especialidade,ativo) values ('am06','HGB-CC-OFTALMO','HGB · CC Oftalmologia','pj50','setor','am05','','OFTALMO',true);
insert into armazens (id,codigo,nome,centro,tipo,pai,responsavel,especialidade,ativo) values ('am07','HGB-CC-GERAL','HGB · CC Cirurgia geral','pj50','setor','am05','','CIRURGIA GERAL',true);
insert into armazens (id,codigo,nome,centro,tipo,pai,responsavel,especialidade,ativo) values ('am08','HGB-AMBULATORIO','HGB · Ambulatório','pj50','setor','am05','','RISCO CX',true);
insert into armazens (id,codigo,nome,centro,tipo,pai,responsavel,especialidade,ativo) values ('am09','HGB-CC-URO','HGB · CC Urologia','pj50','setor','am05','','UROLOGIA',true);
insert into armazens (id,codigo,nome,centro,tipo,pai,responsavel,especialidade,ativo) values ('am10','HGB-CC-OTORRINO','HGB · CC Otorrinolaringologia','pj50','setor','am05','','OTORRINO',true);
insert into armazens (id,codigo,nome,centro,tipo,pai,responsavel,especialidade,ativo) values ('am11','HGB-CC-GINECO','HGB · CC Ginecologia','pj50','setor','am05','','GINECO',true);

-- cargos
insert into cargos (id,nome,cbo,salario_piso) values ('cg01','Assistente administrativo','4110-05',1800);
insert into cargos (id,nome,cbo,salario_piso) values ('cg02','Analista financeiro','2524-05',3200);
insert into cargos (id,nome,cbo,salario_piso) values ('cg03','Auxiliar de escritório','4110-10',1600);
insert into cargos (id,nome,cbo,salario_piso) values ('cg04','Enfermeiro','2235-05',4200);
insert into cargos (id,nome,cbo,salario_piso) values ('cg05','Técnico de enfermagem','3222-05',2400);

-- parâmetros
insert into parametros (chave, valor) values ('tabela_inss', '{"vigencia":"2026-01","faixas":[{"ate":1621,"aliquota":7.5,"deduzir":0},{"ate":2902.84,"aliquota":9,"deduzir":24.32},{"ate":4354.27,"aliquota":12,"deduzir":111.4},{"ate":8475.55,"aliquota":14,"deduzir":198.49}],"teto_contribuicao":988.09}'::jsonb);
insert into parametros (chave, valor) values ('tabela_irrf', '{"vigencia":"2026-01","deducao_por_dependente":189.59,"desconto_simplificado":607.2,"faixas":[{"ate":2428.8,"aliquota":0,"deduzir":0},{"ate":2826.65,"aliquota":7.5,"deduzir":182.16},{"ate":3751.05,"aliquota":15,"deduzir":394.16},{"ate":4664.68,"aliquota":22.5,"deduzir":675.49},{"ate":null,"aliquota":27.5,"deduzir":908.73}],"redutor":{"limite_zera":5000,"limite_fim":7350,"formula_a":978.62,"formula_b":0.133145}}'::jsonb);
insert into parametros (chave, valor) values ('parametros_dp', '{"aliquota_fgts":8,"aliquota_multa_fgts_rescisao":40,"aliquota_inss_patronal":20,"aliquota_rat_fap":1,"aliquota_terceiros":5.8,"terco_constitucional_ferias":0.3333333333333333,"salario_minimo":1621,"teto_salario_familia":1980.38,"valor_salario_familia":67.54,"percentual_vt_max_desconto":6,"divisor_hora_padrao":220}'::jsonb);
insert into parametros (chave, valor) values ('tabela_pate', '[{"id":"pa01","area":"CIRURGIA GERAL","nome":"COLECISTECTOMIA VIDEOLAPAROSCOPICA","codigo":"04.07.03.003-4","sh":746.46,"sp":245.99,"sigtap":992.45,"multiplo":4,"total":3969.8,"faturamento":3771.31,"repasse":688.77,"tipo":"cirurgia"},{"id":"pa02","area":"CIRURGIA GERAL","nome":"HERNIOPLASTIA INGUINAL (BILATERAL)","codigo":"04.07.04.009-9","sh":399.57,"sp":210.49,"sigtap":610.06,"multiplo":4,"total":2440.24,"faturamento":2318.23,"repasse":589.37,"tipo":"cirurgia"},{"id":"pa03","area":"CIRURGIA GERAL","nome":"HERNIOPLASTIA UMBILICAL","codigo":"04.07.04.012-9","sh":298.55,"sp":136.44,"sigtap":434.99,"multiplo":4,"total":1739.96,"faturamento":1652.96,"repasse":382.03,"tipo":"cirurgia"},{"id":"pa04","area":"UROLOGIA","nome":"VASECTOMIA (AMBULATORIAL)","codigo":"04.09.04.024-0","sh":190.92,"sp":247.95,"sigtap":438.87,"multiplo":2,"total":877.74,"faturamento":833.85,"repasse":347.13,"tipo":"cirurgia"},{"id":"pa05","area":"UROLOGIA","nome":"POSTECTOMIA (AMBULATORIAL)","codigo":"04.09.05.008-3","sh":97.92,"sp":121.4,"sigtap":219.32,"multiplo":2,"total":438.64,"faturamento":416.71,"repasse":169.96,"tipo":"cirurgia"},{"id":"pa06","area":"UROLOGIA","nome":"TRATAMENTO CIRURGICO DE HIDROCELE","codigo":"04.09.04.021-5","sh":181.85,"sp":75.12,"sigtap":256.97,"multiplo":4,"total":1027.88,"faturamento":976.49,"repasse":210.34,"tipo":"cirurgia"},{"id":"pa07","area":"UROLOGIA","nome":"TRATAMENTO CIRURGICO DE VARICOCELE","codigo":"04.09.04.023-1","sh":173.24,"sp":84.32,"sigtap":257.56,"multiplo":4,"total":1030.24,"faturamento":978.73,"repasse":236.1,"tipo":"cirurgia"},{"id":"pa08","area":"OFTALMO","nome":"FACOEMULSIFICACAO C/ IMPLANTE DE LENTE INTRA-OCULAR DOBRAVEL","codigo":"04.05.05.037-2","sh":642.96,"sp":128.64,"sigtap":771.6,"multiplo":2,"total":1543.2,"faturamento":1466.04,"repasse":0,"tipo":"cirurgia"},{"id":"pa09","area":"OFTALMO","nome":"EXERESE DE CALAZIO E OUTRAS PEQUENAS LESOES DA PALPEBRA E SUPERCILIOS","codigo":"04.05.01.007-9","sh":55.3,"sp":23.45,"sigtap":78.75,"multiplo":2,"total":157.5,"faturamento":149.62,"repasse":0,"tipo":"cirurgia"},{"id":"pa10","area":"OTORRINO","nome":"SEPTOPLASTIA PARA CORRECAO DE DESVIO","codigo":"04.04.01.048-2","sh":686.36,"sp":303.48,"sigtap":989.84,"multiplo":1,"total":989.84,"faturamento":940.35,"repasse":null,"tipo":"cirurgia"},{"id":"pa11","area":"OTORRINO","nome":"SINUSOTOMIA BILATERAL","codigo":"04.04.01.032-6","sh":616.28,"sp":571.13,"sigtap":1187.41,"multiplo":1,"total":1187.41,"faturamento":1128.04,"repasse":null,"tipo":"cirurgia"},{"id":"pa12","area":"OTORRINO","nome":"TIMPANOPLASTIA (UNI/BILATERAL)","codigo":"04.04.01.035-0","sh":885.96,"sp":968.49,"sigtap":1854.45,"multiplo":1,"total":1854.45,"faturamento":1761.73,"repasse":null,"tipo":"cirurgia"},{"id":"pa13","area":"OTORRINO","nome":"ADENOIDECTOMIA","codigo":"04.04.01.001-6","sh":490.59,"sp":588.51,"sigtap":1079.1,"multiplo":1,"total":1079.1,"faturamento":1025.14,"repasse":null,"tipo":"cirurgia"},{"id":"pa14","area":"OTORRINO","nome":"AMIGDALECTOMIA","codigo":"04.04.01.002-4","sh":521.22,"sp":551.78,"sigtap":1073,"multiplo":1,"total":1073,"faturamento":1019.35,"repasse":null,"tipo":"cirurgia"},{"id":"pa15","area":"OTORRINO","nome":"TURBINECTOMIA","codigo":"04.04.01.041-5","sh":624.38,"sp":448.83,"sigtap":1073.21,"multiplo":1,"total":1073.21,"faturamento":1019.55,"repasse":null,"tipo":"cirurgia"},{"id":"pa16","area":"GINECO","nome":"LAQUEADURA TUBARIA","codigo":"04.09.06.018-6","sh":286.47,"sp":199.01,"sigtap":485.48,"multiplo":2,"total":970.96,"faturamento":922.41,"repasse":278.61,"tipo":"cirurgia"},{"id":"pa17","area":"GINECO","nome":"HISTERECTOMIA VIDEOLAPAROSCOPICA","codigo":"04.09.06.015-1","sh":400.24,"sp":265.08,"sigtap":665.32,"multiplo":2,"total":1330.64,"faturamento":1264.11,"repasse":371.11,"tipo":"cirurgia"},{"id":"pa18","area":"RISCO CX","nome":"RISCO CIRURGICO 6 HORAS - 30 A 35 AGENDAMENTOS","codigo":"","sh":0,"sp":0,"sigtap":0,"multiplo":1,"total":0,"faturamento":0,"repasse":1000,"tipo":"diaria"},{"id":"pa19","area":"OTORRINO","nome":"AMBULATORIO OTORRINO 6 HORAS - 20 A 25 AGENDAMENTOS","codigo":"","sh":0,"sp":0,"sigtap":0,"multiplo":1,"total":0,"faturamento":0,"repasse":1000,"tipo":"diaria"},{"id":"pa20","area":"OTORRINO","nome":"MAPA CIRURGICO DE OTORRINO 12 HORAS - 4 A 5 CIRURGIAS","codigo":"","sh":0,"sp":0,"sigtap":0,"multiplo":1,"total":0,"faturamento":0,"repasse":2000,"tipo":"diaria"},{"id":"pa21","area":"GINECO","nome":"AMBULATORIO GINECO 6 HORAS - 20 A 25 AGENDAMENTOS","codigo":"","sh":0,"sp":0,"sigtap":0,"multiplo":1,"total":0,"faturamento":0,"repasse":1000,"tipo":"diaria"}]'::jsonb);

-- Faltam, de propósito: funcionários (dado pessoal, carga à parte),
-- contratos e ativos reais, e todo o movimento.
